-- Muse DataLoad PostgreSQL schema initialization note.
--
-- The production schema is managed by SQLAlchemy ORM metadata in
-- backend/models.py and created through backend/database.py:init_db().
--
-- Keep this file as a pointer for operators who look for SQL bootstrap
-- material. Do not maintain a second hand-written schema here.
--
-- Typical initialization:
--   1. Create a PostgreSQL database.
--   2. Set DATABASE_URL=postgresql+asyncpg://user:password@host:5432/muse_dataload
--   3. Run any official script, for example:
--        python scripts/build_character_list.py --database-url %DATABASE_URL%
--
-- Scripts call init_db(), which creates the required PostgreSQL tables and
-- indexes from the ORM metadata.
